CREATE TABLE IF NOT EXISTS forensic_intelligence_links (
    id INT UNSIGNED NOT NULL AUTO_INCREMENT,
    citizenid VARCHAR(50) NOT NULL,
    citizen_name VARCHAR(120) DEFAULT NULL,
    case_id INT UNSIGNED DEFAULT NULL,
    report_id INT UNSIGNED DEFAULT NULL,
    scene_id INT UNSIGNED DEFAULT NULL,
    evidence_id INT UNSIGNED DEFAULT NULL,
    source_type VARCHAR(50) NOT NULL,
    source_id INT UNSIGNED DEFAULT NULL,
    match_kind ENUM('dna','digital','arma','capsula','projetil','residuo_polvora','material_biologico') NOT NULL,
    association_level ENUM('vestigio_relacionado','compatibilidade_parcial','compatibilidade_forte','confirmacao') NOT NULL DEFAULT 'compatibilidade_parcial',
    confidence_score DECIMAL(5,2) NOT NULL DEFAULT 0,
    algorithm_name VARCHAR(120) DEFAULT NULL,
    algorithm_version VARCHAR(40) DEFAULT NULL,
    exam_performed_by VARCHAR(50) DEFAULT NULL,
    exam_generated_by VARCHAR(50) DEFAULT NULL,
    exam_origin VARCHAR(120) DEFAULT NULL,
    rationale TEXT DEFAULT NULL,
    metadata LONGTEXT DEFAULT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    KEY idx_fi_citizen (citizenid, created_at),
    KEY idx_fi_case (case_id),
    KEY idx_fi_report (report_id),
    KEY idx_fi_match (match_kind, association_level),
    KEY idx_fi_source (source_type, source_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS forensic_watchlist_events (
    id INT UNSIGNED NOT NULL AUTO_INCREMENT,
    citizenid VARCHAR(50) NOT NULL,
    event_type ENUM('suspect_linked','auto_wanted_added','auto_wanted_removed','profile_seeded') NOT NULL,
    report_id INT UNSIGNED DEFAULT NULL,
    case_id INT UNSIGNED DEFAULT NULL,
    source_module VARCHAR(80) NOT NULL DEFAULT 'forensics',
    source_type VARCHAR(50) DEFAULT NULL,
    source_id INT UNSIGNED DEFAULT NULL,
    reason TEXT DEFAULT NULL,
    algorithm_name VARCHAR(120) DEFAULT NULL,
    algorithm_version VARCHAR(40) DEFAULT NULL,
    confidence_score DECIMAL(5,2) DEFAULT NULL,
    association_level ENUM('vestigio_relacionado','compatibilidade_parcial','compatibilidade_forte','confirmacao') DEFAULT NULL,
    metadata LONGTEXT DEFAULT NULL,
    occurred_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    removed_at TIMESTAMP NULL DEFAULT NULL,
    removed_by VARCHAR(50) DEFAULT NULL,
    PRIMARY KEY (id),
    KEY idx_fw_citizen (citizenid, occurred_at),
    KEY idx_fw_event (event_type),
    KEY idx_fw_report (report_id),
    KEY idx_fw_case (case_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
