-- Atualiza modelos padrão do MDT para PT-BR e estrutura orientada a RP policial brasileiro
-- Mantém suporte multi-idioma: não altera chaves internas, apenas conteúdo exibido ao usuário

DELETE FROM `mdt_report_templates`
WHERE `name` IN ('Standard Incident', 'Traffic Stop', 'Use of Force');

INSERT INTO `mdt_report_templates` (`name`, `type`, `content`, `job_type`) VALUES
('Abordagem Policial', 'Abordagem', '<h2>Resumo da Ocorrência</h2>\n<p>Data/Hora: [DATA_HORA] | Local: [LOCAL] | Guarnição: [EQUIPE]</p>\n\n<h2>Envolvidos</h2>\n<p>Abordado(s): [NOME - RG/CIDADÃO - CONDIÇÃO]</p>\n<p>Testemunha(s): [NOME - CONTATO]</p>\n\n<h2>Materiais Apreendidos</h2>\n<p>[DESCREVER ITEM, QUANTIDADE, SÉRIE E DESTINO]</p>\n\n<h2>Dinâmica</h2>\n<p>[NARRAR FATO EM ORDEM CRONOLÓGICA E OBJETIVA]</p>\n\n<h2>Providências</h2>\n<p>[BUSCAS, CONSULTAS, ORIENTAÇÃO, CONDUÇÃO, AUTUAÇÃO]</p>\n\n<details>\n<summary>Mais detalhes (opcional)</summary>\n<h3>Observações Finais</h3>\n<p>[INFORMAÇÕES COMPLEMENTARES E ENCAMINHAMENTOS]</p>\n</details>', 'leo'),
('Roubo', 'Roubo', '<h2>Resumo da Ocorrência</h2>\n<p>Data/Hora: [DATA_HORA] | Local: [LOCAL] | Natureza: Roubo</p>\n\n<h2>Envolvidos</h2>\n<p>Vítima(s): [NOME - CONTATO - LESÕES]</p>\n<p>Autor(es): [NOME/APELIDO - CARACTERÍSTICAS - DESTINO]</p>\n\n<h2>Materiais Apreendidos</h2>\n<p>[BENS SUBTRAÍDOS/RECUPERADOS, ARMAS, VEÍCULOS]</p>\n\n<h2>Dinâmica</h2>\n<p>[COMO OCORREU A GRAVE AMEAÇA/VIOLÊNCIA E A SUBTRAÇÃO]</p>\n\n<h2>Providências</h2>\n<p>[ISOLAMENTO, DILIGÊNCIAS, BOLETIM, GUIAS, ENCAMINHAMENTOS]</p>\n\n<details>\n<summary>Mais detalhes (opcional)</summary>\n<h3>Observações Finais</h3>\n<p>[IMAGENS, TESTEMUNHAS, CÂMERAS, VÍNCULO COM OUTRAS OCORRÊNCIAS]</p>\n</details>', 'leo'),
('Furto', 'Furto', '<h2>Resumo da Ocorrência</h2>\n<p>Data/Hora: [DATA_HORA] | Local: [LOCAL] | Natureza: Furto</p>\n\n<h2>Envolvidos</h2>\n<p>Vítima(s): [NOME - CONTATO]</p>\n<p>Suspeito(s): [NOME/APELIDO - CARACTERÍSTICAS]</p>\n\n<h2>Materiais Apreendidos</h2>\n<p>[BENS SUBTRAÍDOS/RECUPERADOS, FERRAMENTAS, VEÍCULOS]</p>\n\n<h2>Dinâmica</h2>\n<p>[DESCREVER SUBTRAÇÃO SEM VIOLÊNCIA/AMEAÇA E CIRCUNSTÂNCIAS]</p>\n\n<h2>Providências</h2>\n<p>[DILIGÊNCIAS, PERÍCIA, IMAGENS, REGISTROS COMPLEMENTARES]</p>\n\n<details>\n<summary>Mais detalhes (opcional)</summary>\n<h3>Observações Finais</h3>\n<p>[PONTOS DE INVESTIGAÇÃO E INFORMAÇÕES ADICIONAIS]</p>\n</details>', 'leo'),
('Tráfico de Drogas', 'Tráfico', '<h2>Resumo da Ocorrência</h2>\n<p>Data/Hora: [DATA_HORA] | Local: [LOCAL] | Natureza: Tráfico de Drogas</p>\n\n<h2>Envolvidos</h2>\n<p>Suspeito(s): [NOME - FUNÇÃO - CONDUTA]</p>\n<p>Usuário(s)/Testemunha(s): [NOME - CONTATO]</p>\n\n<h2>Materiais Apreendidos</h2>\n<p>[TIPO DE DROGA, PESO, EMBALAGEM, VALORES, APARELHOS]</p>\n\n<h2>Dinâmica</h2>\n<p>[CONTEXTUALIZAR CAMPANA, FLAGRANTE, VENDA, GUARDA OU TRANSPORTE]</p>\n\n<h2>Providências</h2>\n<p>[PRISÃO, APREENSÃO, LACRE, PERÍCIA, APRESENTAÇÃO À AUTORIDADE]</p>\n\n<details>\n<summary>Mais detalhes (opcional)</summary>\n<h3>Observações Finais</h3>\n<p>[CADEIA DE CUSTÓDIA, TESTES PRELIMINARES, OUTROS INVESTIGADOS]</p>\n</details>', 'leo'),
('Violência Doméstica', 'Violência Doméstica', '<h2>Resumo da Ocorrência</h2>\n<p>Data/Hora: [DATA_HORA] | Local: [LOCAL] | Natureza: Violência Doméstica</p>\n\n<h2>Envolvidos</h2>\n<p>Vítima(s): [NOME - RELAÇÃO - ESTADO FÍSICO/EMOCIONAL]</p>\n<p>Autor(a): [NOME - RELAÇÃO - CONDIÇÃO]</p>\n\n<h2>Materiais Apreendidos</h2>\n<p>[ARMAS, OBJETOS, DOCUMENTOS, REGISTROS]</p>\n\n<h2>Dinâmica</h2>\n<p>[RELATO DA AGRESSÃO, AMEAÇA, CONTEXTO FAMILIAR E RECORRÊNCIA]</p>\n\n<h2>Providências</h2>\n<p>[ACOLHIMENTO, MEDIDAS PROTETIVAS, PRISÃO, ENCAMINHAMENTO À REDE]</p>\n\n<details>\n<summary>Mais detalhes (opcional)</summary>\n<h3>Observações Finais</h3>\n<p>[DECLARAÇÕES, HISTÓRICO, RISCO IMINENTE, CRIANÇAS ENVOLVIDAS]</p>\n</details>', 'leo'),
('Cumprimento de Mandado', 'Cumprimento de Mandado', '<h2>Resumo da Ocorrência</h2>\n<p>Data/Hora: [DATA_HORA] | Local: [LOCAL] | Tipo de Mandado: [PRISÃO/BUSCA]</p>\n\n<h2>Envolvidos</h2>\n<p>Alvo(s): [NOME - ID - SITUAÇÃO]</p>\n<p>Equipe(s): [UNIDADE - INTEGRANTES]</p>\n\n<h2>Materiais Apreendidos</h2>\n<p>[ITENS LOCALIZADOS, ARMAS, DROGAS, DOCUMENTOS]</p>\n\n<h2>Dinâmica</h2>\n<p>[DESCREVER ABORDAGEM, LEITURA DO MANDADO, BUSCAS E REAÇÃO]</p>\n\n<h2>Providências</h2>\n<p>[CUMPRIMENTO FORMAL, CONDUÇÃO, APRESENTAÇÃO, APREENSÕES]</p>\n\n<details>\n<summary>Mais detalhes (opcional)</summary>\n<h3>Observações Finais</h3>\n<p>[Nº DO MANDADO, AUTORIDADE EXPEDIDORA, RESULTADOS COMPLEMENTARES]</p>\n</details>', 'leo'),
('Prisão em Flagrante', 'Flagrante', '<h2>Resumo da Ocorrência</h2>\n<p>Data/Hora: [DATA_HORA] | Local: [LOCAL] | Natureza: Prisão em Flagrante</p>\n\n<h2>Envolvidos</h2>\n<p>Conduzido(s): [NOME - CONDUTA - RESISTÊNCIA]</p>\n<p>Vítima(s)/Testemunha(s): [NOME - CONTATO]</p>\n\n<h2>Materiais Apreendidos</h2>\n<p>[OBJETOS RELACIONADOS AO CRIME, ARMAS, DROGAS, VALORES]</p>\n\n<h2>Dinâmica</h2>\n<p>[NARRAR SITUAÇÃO FLAGRANCIAL E ATOS IMEDIATOS]</p>\n\n<h2>Providências</h2>\n<p>[VOZ DE PRISÃO, DIREITOS, ALGEMAS, CONDUÇÃO, AUTO DE APREENSÃO]</p>\n\n<details>\n<summary>Mais detalhes (opcional)</summary>\n<h3>Observações Finais</h3>\n<p>[INTEGRIDADE FÍSICA, USO DE FORÇA, FILMAGENS E TESTEMUNHAS]</p>\n</details>', 'leo'),
('Confronto Policial', 'Confronto', '<h2>Resumo da Ocorrência</h2>\n<p>Data/Hora: [DATA_HORA] | Local: [LOCAL] | Natureza: Confronto</p>\n\n<h2>Envolvidos</h2>\n<p>Policiais: [NOME - MATRÍCULA - FUNÇÃO]</p>\n<p>Oponente(s): [NOME/APELIDO - SITUAÇÃO]</p>\n\n<h2>Materiais Apreendidos</h2>\n<p>[ARMAS, MUNIÇÕES, VEÍCULOS, OUTROS ITENS]</p>\n\n<h2>Dinâmica</h2>\n<p>[DESCREVER AGRESSÃO INJUSTA, REAÇÃO PROPORCIONAL E CESSAÇÃO]</p>\n\n<h2>Providências</h2>\n<p>[SOCORRO, ISOLAMENTO, PERÍCIA, COMUNICAÇÃO À CORREGEDORIA]</p>\n\n<details>\n<summary>Mais detalhes (opcional)</summary>\n<h3>Observações Finais</h3>\n<p>[CÂMERAS, TRAJETÓRIA, TESTEMUNHAS, PRESERVAÇÃO DE LOCAL]</p>\n</details>', 'leo'),
('Apreensão de Arma', 'Apreensão de Arma', '<h2>Resumo da Ocorrência</h2>\n<p>Data/Hora: [DATA_HORA] | Local: [LOCAL] | Natureza: Apreensão de Arma</p>\n\n<h2>Envolvidos</h2>\n<p>Portador/Responsável: [NOME - SITUAÇÃO LEGAL]</p>\n<p>Equipe: [INTEGRANTES]</p>\n\n<h2>Materiais Apreendidos</h2>\n<p>[TIPO, MARCA, MODELO, CALIBRE, Nº DE SÉRIE, MUNIÇÃO]</p>\n\n<h2>Dinâmica</h2>\n<p>[CIRCUNSTÂNCIA DA LOCALIZAÇÃO E APREENSÃO]</p>\n\n<h2>Providências</h2>\n<p>[CONFERÊNCIA, LACRE, CADASTRO, ENCAMINHAMENTO AO DEPÓSITO]</p>\n\n<details>\n<summary>Mais detalhes (opcional)</summary>\n<h3>Observações Finais</h3>\n<p>[POSSÍVEL VÍNCULO COM OUTROS CRIMES E SOLICITAÇÃO DE PERÍCIA]</p>\n</details>', 'leo'),
('Apreensão de Droga', 'Apreensão de Droga', '<h2>Resumo da Ocorrência</h2>\n<p>Data/Hora: [DATA_HORA] | Local: [LOCAL] | Natureza: Apreensão de Droga</p>\n\n<h2>Envolvidos</h2>\n<p>Suspeito(s): [NOME - CONDIÇÃO]</p>\n<p>Testemunha(s): [NOME - CONTATO]</p>\n\n<h2>Materiais Apreendidos</h2>\n<p>[TIPO, PESO, PORCIONAMENTO, EMBALAGEM, VALORES, APETRECHOS]</p>\n\n<h2>Dinâmica</h2>\n<p>[COMO A SUBSTÂNCIA FOI LOCALIZADA E A CONTEXTUALIZAÇÃO]</p>\n\n<h2>Providências</h2>\n<p>[LACRE, TESTE PRELIMINAR, REGISTRO, ENCAMINHAMENTO PERICIAL]</p>\n\n<details>\n<summary>Mais detalhes (opcional)</summary>\n<h3>Observações Finais</h3>\n<p>[CADEIA DE CUSTÓDIA, NÚMERO DE VOLUMES, FOTOS]</p>\n</details>', 'leo'),
('Homicídio', 'Homicídio', '<h2>Resumo da Ocorrência</h2>\n<p>Data/Hora: [DATA_HORA] | Local: [LOCAL] | Natureza: Homicídio</p>\n\n<h2>Envolvidos</h2>\n<p>Vítima(s): [NOME - CONDIÇÃO NO LOCAL]</p>\n<p>Suspeito(s): [NOME/APELIDO - CARACTERÍSTICAS]</p>\n\n<h2>Materiais Apreendidos</h2>\n<p>[ARMAS, PROJÉTEIS, CÁPSULAS, VESTÍGIOS, IMAGENS]</p>\n\n<h2>Dinâmica</h2>\n<p>[RECONSTRUÇÃO INICIAL DOS FATOS E LINHA DO TEMPO]</p>\n\n<h2>Providências</h2>\n<p>[ISOLAMENTO, PERÍCIA, IML, DILIGÊNCIAS, COMUNICAÇÃO À AUTORIDADE]</p>\n\n<details>\n<summary>Mais detalhes (opcional)</summary>\n<h3>Observações Finais</h3>\n<p>[POSSÍVEIS MOTIVAÇÕES, TESTEMUNHAS, CÂMERAS, HIPÓTESES]</p>\n</details>', 'leo'),
('Acidente de Trânsito', 'Acidente de Trânsito', '<h2>Resumo da Ocorrência</h2>\n<p>Data/Hora: [DATA_HORA] | Local: [LOCAL] | Natureza: Acidente de Trânsito</p>\n\n<h2>Envolvidos</h2>\n<p>Condutor(es): [NOME - HABILITAÇÃO - ESTADO]</p>\n<p>Vítima(s)/Passageiro(s): [NOME - LESÕES]</p>\n\n<h2>Materiais Apreendidos</h2>\n<p>[VEÍCULOS ENVOLVIDOS, DOCUMENTOS, OBJETOS, IMAGENS]</p>\n\n<h2>Dinâmica</h2>\n<p>[DESCREVER CONDIÇÕES DA VIA, SINALIZAÇÃO, MANOBRAS E IMPACTO]</p>\n\n<h2>Providências</h2>\n<p>[SINALIZAÇÃO DA VIA, SOCORRO, TESTES, REMOÇÃO, AUTUAÇÕES]</p>\n\n<details>\n<summary>Mais detalhes (opcional)</summary>\n<h3>Observações Finais</h3>\n<p>[CROQUI, LAUDO, TESTEMUNHAS, CÂMERAS E RESPONSABILIZAÇÃO]</p>\n</details>', 'leo')
ON DUPLICATE KEY UPDATE
`content` = VALUES(`content`),
`type` = VALUES(`type`),
`job_type` = VALUES(`job_type`),
`updated_at` = CURRENT_TIMESTAMP();
